# Generated by Django 4.2.7 on 2025-07-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='tip_files/'),
        ),
    ]
