# Generated by Django 4.2.7 on 2025-07-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecoaction',
            name='rejection_comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
