# Generated by Django 4.2.7 on 2025-07-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_ecoaction_rejection_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecoaction',
            name='last_approved_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
